name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: 98.81.142.211
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/backend-chatbot
            git pull
            npm install
            pm2 restart server
